name:                nntp
version:             0.2.0.0
github:              "Pankrip/nntp"
license:             MIT
author:              "Patryk Węgrzyn, Błażej Lepiarczyk"
maintainer:          "example@example.com"
copyright:           "2018 Patryk Węgrzyn, Błażej Lepiarczyk"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/Pankrip/nntp#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- network
- yaml-config
- unix
- unix-bytestring
- unordered-containers
- QuickCheck
- hspec
- hspec-discover
- hspec-core
- regex-posix
- split
- quickcheck-instances
- text
- dates
- aeson

library:
  source-dirs: src

executables:
  nntp-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -rtsopts
    - -with-rtsopts=-N
    - -threaded
    - -static
    dependencies:
    - nntp

tests:
  nntp-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nntp
